{
 "title": "Services statistic",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  { "title": "Hikari", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "hikaricp_connections_active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hikaricp_connections_pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_pending)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hikaricp_connections_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sum(hikaricp_connections_max)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "hikaricp_connections_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payments outcome rate per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(payment_finished_total{service=~\"$service\"}[30s])) by (service, outcome, failReason)",
       "legendFormat": "{{outcome}} - {{failReason}}"
      }
     ]
    },
    {
     "title": "Event during testing per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (type) (rate(events_total{}[30s]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Income / Expenses percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1217 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
       "legendFormat": "expenses - {{service}} "
      }
     ]
    },
    {
     "title": "Income / Expenses percentage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1217 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
       "legendFormat": "expenses - {{service}} "
      }
     ]
    },
    {
     "title": "Income / Expenses amount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1225 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service, accountName) ",
       "legendFormat": "expenses - {{service}} - {{accountName}}"
      }
     ]
    },
    {
     "title": "Income / Expenses amount",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1225 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service, accountName) ",
       "legendFormat": "expenses - {{service}} - {{accountName}}"
      }
     ]
    }
   ]
  },
  { "title": "Tests info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Tests run",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(test_duration_count{service=~\"$service\"}[$__range])) by (service, testOutcome)",
     "legendFormat": "{{service}} - {{testOutcome}}"
    }
   ]
  },
  {
   "title": "Success percent (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(service)(increase(test_duration_count{service=~\"$service\", testOutcome=~\"SUCCESS\"}[1m]))) / (sum by(service) (increase(test_duration_count{service=~\"$service\", testOutcome=~\".*\"}[1m])))",
     "legendFormat": "{{service}} - success"
    }
   ]
  },
  {
   "title": "Average test duration by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(test_duration_sum{service=~\"$service\"}[1m])) by (service, testOutcome) / sum by (service, testOutcome) (rate(test_duration_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{testOutcome}}"
    }
   ]
  },
  { "title": "Stages info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Success stages number per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(stage_duration_ok_count{service=~\"$service\", result=\"success\"}[1m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Fail stages number per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(stage_duration_ok_count{service=~\"$service\", result=\"failed\"}[1m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Success stages duration. Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(stage_duration_ok_sum{service=~\"$service\", result=\"success\"}[1m]) / rate(stage_duration_ok_count{service=~\"$service\", result=\"success\"}[1m])",
     "legendFormat": "{{stage}}"
    },
    {}
   ]
  },
  { "title": "Http calls info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "(Clients -> Online shop) http requests processed rate (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_external_duration_count{service=~\"$service\"}[30s])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "(Clients -> Online shop) http requests duration. Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_external_duration_sum{service=~\"$service\"}[1m]) / rate(http_external_duration_count{service=~\"$service\"}[1m])",
     "legendFormat": "{{method}} - {{result}}"
    }
   ]
  },
  {
   "title": "(Online shop -> Payment system)  http requests processed rate (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(external_sys_duration_count{service=~\"$service\"}[30s])",
     "legendFormat": "{{accountName}} - {{outcome}}"
    }
   ]
  },
  {
   "title": "(Online shop -> Payment system)  Payment sys processing duration. Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(external_sys_duration_sum{service=~\"$service\"}[1m]) / rate(external_sys_duration_count{service=~\"$service\"}[1m])",
     "legendFormat": "{{accountName}} - {{outcome}}"
    }
   ]
  },
  {
   "title": "(Test system -> Online shop)  Average request latent time (before submit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_latent_sum{service=~\"$service\"}[15s]) / rate(http_request_latent_count{service=~\"$service\"}[15s])",
     "legendFormat": "{{method}} - {{result}}"
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 957 },
     "targets": [
      {
       "expr": "max by (name) (executor_queued_tasks{service=~\"$service\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Completed tasks rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 957 },
     "targets": [
      {
       "expr": "sum by (name) (rate(executor_completed_tasks_total{}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Active executors threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1037 },
     "targets": [
      {
       "expr": "sum by (name) (executor_active_threads{})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage (XMX%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 958 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum ((sum by (job, area) (jvm_memory_used_bytes{area=\"heap\"}) / sum by (job, area) (jvm_memory_max_bytes{area=\"heap\"})) * 100) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "JVM threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 958 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (jvm_threads_live_threads{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 990 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (system_cpu_usage{service=~\"$service\"})",
       "legendFormat": "{{job}} - System CPU Usage"
      },
      {
       "expr": "sum by (job) (process_cpu_usage{service=~\"$service\"})",
       "legendFormat": "{{job}} -Process CPU Usage"
      }
     ]
    },
    {
     "title": "GC delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 990 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{}[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 998 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (process_files_open_files{})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 959 },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_config_max{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Thread Config Min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 959 },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_config_min{service=~\"$service\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Jetty Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 967 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_busy{})",
       "legendFormat": "{{job}} -  busy "
      },
      {
       "expr": "sum by (job) (jetty_threads_idle{})",
       "legendFormat": "{{job}} - idle"
      },
      {
       "expr": "sum by (job) (jetty_threads_current{})",
       "legendFormat": "{{job}} - current"
      },
      {
       "expr": "sum by (job) (jetty_threads_jobs{})",
       "legendFormat": "{{job}} - jobs"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 975 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{service=~\"$service\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 975 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job, method, status, uri) (irate(http_server_requests_seconds_sum{service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}} - {{job}}"
      }
     ]
    }
   ]
  }
 ]
}